### ISSUE TITLE
Parameters missing "maxLength", "nullable" props output, Type 'object' no longer notated

### ISSUE THREAD

**Issue by simranbentel** [cloud-annotations/docusaurus-plugin-openapi#100]
In latest v0.3.0 release, `object` type is no longer notated in the table of parameters (previously, the top level `amount` param had "object" type notated:
![Screen Shot 2021-12-16 at 1 55 07 PM](https://user-images.githubusercontent.com/6208651/146455197-ad1266d5-f145-4199-9c53-406211901a38.png)

Another couple of props are missing from the output. For example, given this param:

`"correlationId": {
  "maxLength": 40,
  "type": "string",
  "description": "Invoice correlation id",
  "nullable": true,
}`

Actual output:
![Screen Shot 2021-12-16 at 2 03 57 PM](https://user-images.githubusercontent.com/6208651/146455824-aa71f617-eb56-4909-86c9-599591e98d6e.png)

Expected:
<img width="1087" alt="Screen Shot 2021-12-16 at 2 04 33 PM" src="https://user-images.githubusercontent.com/6208651/146455861-1b7dc3fc-3814-4cfd-9008-0d8dcd40a022.png">
The "Nullable" and maxLength are being omitted.

**Comment by bourdakos1** [comment]
> In latest v0.3.0 release, object type is no longer notated in the table of parameters (previously, the top level amount param had "object" type notated

This doesn't look like a regression, I'm still seeing the proper schema name listed for objects. I'm guessing this is a bug for schema using `allOf`. I'll test it out and try to fix.

> The "Nullable" and maxLength are being omitted.

Is `nullable` different from not being `required`?

**Comment by bourdakos1** [comment]
For `allOf` the name of the schema is slightly complicated, because it is a list of schema:
```yaml
name: pet
schema:
  allOf:
    - $ref: "#/components/schemas/Cat"
    - $ref: "#/components/schemas/Dog"
    - $ref: "#/components/schemas/Goldfish"
```

In your opinion, should this render as:

`pet` Cat & Dog & Goldfish

or just:

`pet` object

**Comment by simranbentel** [comment]
> > In latest v0.3.0 release, object type is no longer notated in the table of parameters (previously, the top level amount param had "object" type notated
> 
> This doesn't look like a regression, I'm still seeing the proper schema name listed for objects. I'm guessing this is a bug for schema using `allOf`. I'll test it out and try to fix.
> 
> > The "Nullable" and maxLength are being omitted.
> 
> Is `nullable` different from not being `required`?

Indeed nullable is not required. As long as required is displayed nullable is not needed. My mistake.

**Comment by bourdakos1** [comment]
Okay cool, #102 should fix the `allOf` issue. I'll open another PR to add support for the following qualifiers (let me know if I missed anything important):
- maxLength
- minLength
- maximum
- minumum
- exclusiveMaximum
- exclusiveMinimum
- maxItems
- minItems
- uniqueItems
- maxProperties
- minProperties
- multipleOf
- pattern

if you have a schema with:
```yaml
slug:
  type: string
  description: The human-readable, unique identifier, used to identify the document.
  minLength: 1
  maxLength: 40
  pattern: "^[a-zA-Z0-9_-]*$"
  required: true
```

would render:

<table><tbody><tr><td>

`slug` string - REQUIRED

**Possible values:** 1 ≤ length ≤ 40, Value must match regular expression `^[a-zA-Z0-9_-]*$`

The human-readable, unique identifier, used to identify the document.

</td></tr></tbody></table>
