### ISSUE TITLE
Feature request: Endpoints in menu should display method tags

### ISSUE THREAD

**Issue by simranbentel** [cloud-annotations/docusaurus-plugin-openapi#101]
It is common for API documentation to display endpoint methods (GET, POST, etc...) in the menu, example:
![Screen Shot 2021-12-16 at 2 10 47 PM](https://user-images.githubusercontent.com/6208651/146456450-9c75afa8-0742-4042-a67f-4c61261c85ec.png)

**Comment by bourdakos1** [comment]
I'm not sure if this is possible with the docusaurus sidebar. Possibly with some css magic? I think I might be able to provide classnames `get` `post` `put` etc.. to the links and then you could have styles like `.get::before { content: "GET" }`. Would that work for you?

**Comment by bchmnn** [comment]
The guys from [redocusaurus](https://github.com/rohit-gohri/redocusaurus) managed to get tags in the sidebar working: [demo](https://rohit-gohri.github.io/redocusaurus/examples/using-spec-yaml/).

**Comment by bourdakos1** [comment]
@bchmnn redocusaurus doesn’t use the native Docusaurus sidebar. I could build my own sidebar to achieve the same effect, but that’s not an approach I would like to take.

**Comment by bchmnn** [comment]
@bourdakos1 Ah okay. Understandable. :)

**Comment by simranbentel** [comment]
> I'm not sure if this is possible with the docusaurus sidebar. Possibly with some css magic? I think I might be able to provide classnames `get` `post` `put` etc.. to the links and then you could have styles like `.get::before { content: "GET" }`. Would that work for you?

That would be a very good solution.

**Comment by bourdakos1** [comment]
Awesome, I'll open a PR adding classnames and leave the styling up to you

**Comment by sserrata** [comment]
If it's helpful to anyone, our team managed to get method labels working with the Docusaurus sidebar using `customProps` and some CSS magic.

API docs: https://prisma.pan.dev/api/cloud
Repo: https://github.com/PaloAltoNetworks/prisma.pan.dev
CSS: https://github.com/PaloAltoNetworks/prisma.pan.dev/blob/master/src/css/custom.css#L540
Sidebar: https://github.com/PaloAltoNetworks/prisma.pan.dev/blob/master/static/oas/cspm/sidebar.js#L58

**Comment by bourdakos1** [comment]
Awesome! Glad to know this will work :)
