### ISSUE TITLE
Fails to install with Yarn 3: "Error: Assertion failed: Expected the root to be registered"

### ISSUE THREAD

**Issue by JaimeObregon** [cloud-annotations/docusaurus-plugin-openapi#118]
I am using Yarn 3.1.1 and on a fresh Docusaurus install, `yarn add docusaurus-preset-openapi` yields this error:

```
Error: Assertion failed: Expected the root to be registered
```

To reproduce, put this `pacakge.json` in an empty directory and run `yarn install && yarn add docusaurus-preset-openapi` afterwards:

```json
{
  "name": "my-package",
  "packageManager": "yarn@3.1.1",
  "dependencies": {
    "@docusaurus/core": "2.0.0-beta.14",
    "@docusaurus/preset-classic": "2.0.0-beta.14",
    "@mdx-js/react": "^1.6.21",
    "clsx": "^1.1.1",
    "prism-react-renderer": "^1.2.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  }
}
```

However, it works fine with Yarn 1.22 (a version no longer under active development), if this line is removed:

```
  "packageManager": "yarn@3.1.1",
```

**Comment by JaimeObregon** [comment]
Update: it still fails when Docusaurus version is set to `latest`:

```
    "@docusaurus/core": "latest",
    "@docusaurus/preset-classic": "latest",
```

**Comment by bourdakos1** [comment]
Thanks, I will try to reproduce and fix 😊

**Comment by bourdakos1** [comment]
reproduced!

**Comment by bourdakos1** [comment]
I was able to get it to install using `"@docusaurus/core": "2.0.0-beta.13"`:
```json
{
  "name": "my-package",
  "packageManager": "yarn@3.1.1",
  "dependencies": {
    "@docusaurus/core": "2.0.0-beta.13",
    "@mdx-js/react": "^1.6.21",
    "clsx": "^1.1.1",
    "docusaurus-preset-openapi": "0.3.1",
    "prism-react-renderer": "^1.2.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  }
}
```

I'm guess the issue is because we depend on `"2.0.0-beta.13"` internally?

**Comment by JaimeObregon** [comment]
Thank you, @bourdakos1! With `2.0.0-beta.13` it does work wonderfully 👍.
