### ISSUE TITLE
openapiPath directory resolution

### ISSUE THREAD

**Issue by avaidyam** [cloud-annotations/docusaurus-plugin-openapi#26]
Interestingly, the `openapiPath` doesn't work if I just provide a raw string (relative to the root of the repo directory). I have to this to make it work: 

```
module.exports.plugins[0][1].openapiPath = require.resolve(module.exports.plugins[0][1].openapiPath); 
``` 

What kind of raw path is expected for it to work? Something like `../../../openapi.json`?

**Comment by bourdakos1** [comment]
`require.resolve` resolves the file to an absolute path

**Comment by avaidyam** [comment]
@bourdakos1 Is there some way to make it so if the import fails it tries again after using `require.resolve`?

**Comment by bourdakos1** [comment]
@avaidyam I updated how we import the OpenAPI definition, so you now provide a raw string relative to the siteDir. Does this resolve your issue?

```diff
- openapiPath: require.resolve("./examples/openapi.json")
+ path: "examples/openapi.json"
```

**Comment by avaidyam** [comment]
I think this should work! Thanks.

**Comment by avaidyam** [comment]
@bourdakos1 Actually, could you please create a new release so that I can test this out?

**Comment by bourdakos1** [comment]
There’s a few breaking changes in master so I want to wait a little bit longer to make sure everything is finalized before cutting a release
