### ISSUE TITLE
Doesn't work with 2.0.0-beta.0

### ISSUE THREAD

**Issue by avaidyam** [cloud-annotations/docusaurus-plugin-openapi#31]
Not really sure why, but when using `npm start` the page entirely doesn't load, and when using `npm run build`, the page displays but without the API console on the right-hand side.

**Comment by matheusbaumgart** [comment]
Same issue here with the page not loading (forever loading).

```
"dependencies": {
    "@docusaurus/core": "2.0.0-beta.4",
    "@docusaurus/preset-classic": "2.0.0-beta.4",
    "@mdx-js/react": "^1.6.21",
    "@svgr/webpack": "^5.5.0",
    "clsx": "^1.1.1",
    "docusaurus-plugin-openapi": "^0.0.16",
    "file-loader": "^6.2.0",
    "prism-react-renderer": "^1.2.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "url-loader": "^4.1.1"
  },
```

**Comment by bourdakos1** [comment]
Just an update on this, I made a lot of progress yesterday. I believe the bulk of the issues were due to webpack 5. Additionally, I need to rewrite the sidebar component to be compatible.

**Comment by avaidyam** [comment]
@bourdakos1 In an interesting coincidence, I've done the same. It's almost working on my end with beta9.

**Comment by bourdakos1** [comment]
oh great to hear! I'll put a pause on my end then

**Comment by bourdakos1** [comment]
@avaidyam I opened a draft PR with my work so far if its any help https://github.com/cloud-annotations/docusaurus-plugin-openapi/pull/50

**Comment by avaidyam** [comment]
@bourdakos1 I've opened #51 which solves this issue (and a LOT of other minor annoyances/potential major issues).
