### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by braden-clerk** [cloud-annotations/docusaurus-plugin-openapi#4]
Hey this looks great, but having trouble installing it (new to react && docusaurus). followed the steps on the readme, but it's just 404ing -- is there a build step i need to run?

**Comment by bourdakos1** [comment]
Does the Docusaurus UI show up with a 404? Or is it just a blank white page 404?

If you run “yarn start” or “npm run start” it should do a dev build and serve the pages on localhost. You can run “yarn build” to build the static pages.

**Comment by braden-clerk** [comment]
Hey thanks for the reply! I actually figured it out.
the routeBasePath in this preset for some reason messed with docusaurus-plugin-api ... removing that routeBasePath resolved it


`    [
      "@docusaurus/preset-classic",
      {
        docs: {
          routeBasePath: "",
          sidebarPath: require.resolve("./sidebars.js"),
        },
        theme: {
          customCss: require.resolve("./src/css/custom.css"),
        },
      },
    ],`
