### ISSUE TITLE
Upgrade this plugin to docusaurus beta

### ISSUE THREAD

**Issue by paresh-huma** [cloud-annotations/docusaurus-plugin-openapi#49]
We have used this plugin that meets our requirements the way we want to create and manage the entire platform documentation. We have got this plugin working end-to-end for the Alpha version of Docusaurus but it's being deprecated and we couldn't find a way to make it work for the Beta version of Docusaurus.

We are really looking forward someone who can make this plugin work for the Beta version of Docusaurus and we are happy to sponsor the development charges. We will then open-source it here for the community. 

Please get back to me if this is something you can help us and the community. We really believe this plug-in is very valuable for the community.

**Comment by bourdakos1** [comment]
I will take a closer look at this and try to get this working. Closing this issue in favor of #31
