### ISSUE TITLE
Supporting more than one openapi spec

### ISSUE THREAD

**Issue by ymolists** [cloud-annotations/docusaurus-plugin-openapi#5]
It seems right now the plugin only supports one spec at a time. I am wondering if it would be possible to add more than one openapi spec at a time. The alternative is to hos the api documentation in multiple docusaurus instances which is not ideal in all cases.

Thank you so much for considering this !!!

**Comment by guillermotti** [comment]
Yes! That would be awesome. We have different APIs, each one with a different OpenAPI definition.

We would like to select the endpoint for each OpenAPI definition like:

`plugins: [
  ["docusaurus-plugin-openapi", 
  {
    openapiPath: require.resolve("./definition1.json"),
  }, 
  {
    openapiPath: require.resolve("./definition2.json"),
  }],
]`

And this could be resolved at **/api/definition1** and **/api/definition2**.
 
By the way, this plugin its amazing!! Exactly what we were looking for. Thanks in advance!

**Comment by guillermotti** [comment]
Well, I realised that the plugin already provides this functionality:

` plugins: [
    'docusaurus-plugin-sass',
    '@cmfcmf/docusaurus-search-local',
    ["docusaurus-plugin-openapi", {
      id: 'plugin-1',
      openapiPath: require.resolve("./openapi1.json"), routeBasePath: 'cars',
    }],
    ["docusaurus-plugin-openapi", {
      id: 'plugin-2',
      openapiPath: require.resolve("./openapi2.json"), routeBasePath: 'bikes',
    }]
  ],`

And this is resolved at http://localhost:3000/cars and http://localhost:3000/bikes.

The id for the plugin is mandatory: https://v2.docusaurus.io/docs/using-plugins/#multi-instance-plugins-and-plugin-ids

**Comment by guillermotti** [comment]
I added this PR to improve README doc: https://github.com/cloud-annotations/docusaurus-plugin-openapi/pull/6

**Comment by bourdakos1** [comment]
Thanks for the help @guillermotti 😁 I merged your PR
