### ISSUE TITLE
UI quirks, new?

### ISSUE THREAD

**Issue by afterthought** [cloud-annotations/docusaurus-plugin-openapi#54]
The narrow tables in the middle and the menu indicator in the sidebar are not in the screenshot in the readme. Are these new after the recent upgrade? Or maybe something about how I launched the demo?

<img width="1816" alt="Screen Shot 2021-11-08 at 8 51 47 PM" src="https://user-images.githubusercontent.com/198010/140847192-dd8ef50c-ecc3-4de7-8a59-33e2a4c1e215.png">

**Comment by bourdakos1** [comment]
Yea I believe this is a regression from the 0.1.0 release. I’ll work on fixing this

**Comment by afterthought** [comment]
Thanks. I have a list of features/changes that I want to help with. Are you open to PR's for any of these?

- Allow runtime configuration for servers and security (not sure about this, but we might have different OpenAPI spec files per client. the differences should just be server host names and maybe slight variations in auth schemes)
- Support for client_credentials OAUTH flow
- An option to persist credentials (local storage) to make interactive API exploration a little more user friendly
- Both #16 and #8.

**Comment by afterthought** [comment]
Thanks. I will open issues. I might wait until I know I'll have a chance to do the work.

**Comment by bourdakos1** [comment]
Both the narrow table bug and sidebar issue have been fixed and should be available in the next release
