### ISSUE TITLE
support for trailingSlash=false

### ISSUE THREAD

**Issue by afterthought** [cloud-annotations/docusaurus-plugin-openapi#56]
Reference: https://docusaurus.io/docs/deployment#trailing-slashes

We use a hosting provider that requires this setting to be false. When false, the OpenAPI plugin does not show its sidebar. I can remove the config to fix the OpenAPI plugin, but that breaks the docs/ sidebar.

**Comment by bourdakos1** [comment]
I think this might be fixed on the main branch. I'll be releasing 0.2.0 soon, which will have a few breaking changes, but it seems like the trailing slash issue is gone

**Comment by bourdakos1** [comment]
I think this is fixed. Feel free to reopen if you're still experiencing this issue :)
