### ISSUE TITLE
Nested tags

### ISSUE THREAD

**Issue by Anthony-Gaudino** [cloud-annotations/docusaurus-plugin-openapi#59]
Is it possible to have nested tags, and then have them displayed on the navigation menu?

For example if I would like to have for example `cat` and `dog` bellow `pets` and then have the endpoints bellow each one:
![](https://user-images.githubusercontent.com/4212769/85324376-b9e3d900-b497-11ea-9765-c42a8ad1ff61.png)

**Comment by bourdakos1** [comment]
We don't have support for this at the moment. I don't think OpenAPI's `tags` has the intrinsic capability of expressing hierarchy, so if we wanted to tackle this we would need to extend the spec in some way. 

I don't see myself having the time to work on a feature like this, so I'm going to close this issue. Feel free to reopen if this is a feature you would like to help contribute.
