### ISSUE TITLE
Base URL for endpoint test UI & Execute calls

### ISSUE THREAD

**Issue by simranbentel** [cloud-annotations/docusaurus-plugin-openapi#66]
I do not see any config for setting the base url that is used in the endpoint testing UI (2nd column). The default behavior appears to be to use the same url that the site is running on. So when developing it attempts to call localhost... and when deployed it calls that url. I tried adding "servers.url" in the swagger json but that does not appear to be used either. Any input you can provide?

**Comment by bourdakos1** [comment]
Adding urls to servers should give you a dropdown to choose a base url in the testing UI. Here's an example OpenAPI definition that uses servers:

https://github.com/cloud-annotations/docusaurus-plugin-openapi/blob/d39424f3b6150d09a2f0bb4f2349d16508840c43/demo/examples/openapi-cos.json#L175

Do you have a sample OpenAPI definition you feel comfortable sharing that isn't respecting the `servers` stanza?

**Comment by simranbentel** [comment]
Thank you for the fast response!! I had a syntax error in my swagger json (servers was not an array). Works now!
