### ISSUE TITLE
I'd love to contribute!

### ISSUE THREAD

**Issue by lauzierj** [cloud-annotations/docusaurus-plugin-openapi#7]
Hi there,

I wasn't sure what the best way to reach out was, but I'd love to contribute.

I noticed that the version published to npm was 0.0.12 while what's in master is 0.0.10. 

I'd like to add support for OpenAPI's `allOf` syntax.

**Comment by bourdakos1** [comment]
oh yup thanks, forgot to push my committed changes haha :)

Feel free to open a PR, I'd be more than happy to merge any enhancements

**Comment by bourdakos1** [comment]
@lauzierj we support `allOf` now fyi
