### ISSUE TITLE
Site description content is not being displayed.

### ISSUE THREAD

**Issue by simranbentel** [cloud-annotations/docusaurus-plugin-openapi#89]
We have important content in the `info.description` section of the swagger json. This content is not currently being displayed. The documentation makes no mention of displaying static content. Is there somewhere else in the json this content should be placed so that it will display? Is there some other way to include static pages with navigation side by side with the dynamic endpoint content?

Expected:
The content in `info.description` should be displayed, with sections determined by the markdown.

Actual:
The content is ignored.

**Comment by bourdakos1** [comment]
@simranbentel I plan on adding support for this soon. I'm going to close this, because we are already tracking here: #8

**Comment by simranbentel** [comment]
> @simranbentel I plan on adding support for this soon. I'm going to close this, because we are already tracking here: #8

Thanks, can I get an idea of the timing? The display of this content is needed for us to launch our site.

**Comment by bourdakos1** [comment]
I normally only have time on the weekend, so definitely by the end of the week. Maybe sooner if I get some time during the week.
