### ISSUE TITLE
Allow markdown in paramater descriptions

### ISSUE THREAD

**Issue by isaiahdahl** [cloud-annotations/docusaurus-plugin-openapi#95]
I want to be able to document query parameters like this:

![CleanShot 2021-12-14 at 10 31 51](https://user-images.githubusercontent.com/23046374/146059194-b062ea6f-406c-4ee1-aadb-15d8bdb3e3ea.png)

To be able to do this I would need markdown support for description in parameters.

**Comment by bourdakos1** [comment]
The parameter descriptions support markdown. Are you having issues getting it working?

**Comment by isaiahdahl** [comment]
Very odd. I couldn't get it to work yesterday so I pulled out all the markdown from my descriptions. Now I just go and try again and it works and I can't recreate it. Not sure what happened, I'll re-open if I can recreate in future. Thanks for clarifying.
